name: GitHub Actions Example
on: [push]
jobs:
    Explore-GitHub-Actions:
        runs-on: ubuntu-latest
        steps:
            - name: A
              run: echo " The job was automatically triggered by a ${{Github.event_name }} event."
            - name: B
              run: echo " This job is now running on a ${{ runner.os }} server hosted by GitHub!"
            - name: C
              run: echo " The name of your branch is ${{ GitHub.ref }} and your repository is ${{ GitHub.repository }}."

            - name: Check out repository code
              uses: actions/checkout@v3
            - name: D
              run: echo " The ${{ GitHub.repository }} repository has been cloned to the runner." 
            - name: E
              run: echo " The workflow is now ready to test your code on the runner."

            - name: List files in the repository
              run: |
                Is ${{ GitHub.workspace }}
            - name: F
              run: echo " This job's status is ${{ job.status }}."
